package it.epicode.capstone.degree_courses;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.ApplicationArguments;
import org.springframework.boot.ApplicationRunner;
import org.springframework.stereotype.Component;

import java.util.Arrays;
import java.util.List;

public class DegreeCourseRunner implements ApplicationRunner {

    @Autowired
    private DegreeCourseService degreeCourseService;

    @Override
    public void run(ApplicationArguments args) throws Exception {

        List<String> degreeCourses = Arrays.asList(
                "Agricultural Sciences",
                "Animal Breeding Techniques and Dog Training",
                "Animal Production Science and Technology",
                "Veterinary Medicine",
                "Viticulture and Enology",
                "Cultural Heritage Studies",
                "Digital Humanities",
                "Historical Studies",
                "Humanities",
                "Italian Language and Culture for Foreigners",
                "Languages, Literatures and Intercultural Communications",
                "Philosophy",
                "Primary Teacher Education",
                "Sciences for Peace: International Cooperation and Conflict Transformation",
                "Studies in Performing Arts and Communication",
                "Aerospace Engineering",
                "Architecture and Building Engineering",
                "Biomedical Engineering",
                "Chemical Engineering",
                "Civil-Environmental and Building Engineering",
                "Computer Engineering",
                "Electronic Engineering",
                "Energy Engineering",
                "Engineering for The Industrial Design",
                "Engineering Management",
                "Mechanical Engineering",
                "Maritime and Naval Science",
                "Techniques for Civil Construction and Land Management",
                "Techniques for Mechanics and Production",
                "Telecommunications Engineering",
                "Audioprothesic Techniques",
                "Biomedical Laboratory Techniques",
                "Childhood Neuro and Psycomotricity",
                "Dental Hygiene",
                "Dentistry and Dental Prosthodontics",
                "Dietistic",
                "Environment and Workplace Prevention Techniques",
                "Imaging and Radiotherapy Techniques",
                "Medicine and Surgery",
                "Midwifery",
                "Nursing",
                "Pharmaceutical Chemistry and Technology",
                "Pharmacy",
                "Physiotherapy",
                "Podiatry",
                "Psychiatric Rehabilitation Techniques",
                "Science of Herbal and Health Products",
                "Sciences and Techniques in Clinical and Experimental Psychology",
                "Speech and Language Therapy",
                "Sports and Physical Education",
                "Banking Finance and Financial Markets",
                "Business Studies",
                "Business, Work and Administrative Legal Services",
                "Economics and Commerce",
                "Law",
                "Management and Law of Logistics Systems",
                "Management for Business Economics",
                "Political Science",
                "Science of Social Work",
                "Tourism Sciences",
                "Biological Sciences",
                "Biotechnology",
                "Chemistry",
                "Chemistry for Industry and Environment",
                "Computer Science",
                "Geological Sciences",
                "Geology",
                "Mathematics",
                "Natural and Environmental Sciences",
                "Physics",
                "Food Biosafety and Quality",
                "Plant and Microbe Biotechnologies",
                "Sustainability of Animal Production Systems",
                "Sustainable Agricultural Systems",
                "Urban Green Areas and Landscape Planning and Management",
                "Archeology Studies",
                "Art History",
                "Classical Philology and Ancient History",
                "Communication, Media, Technologies",
                "Digital Humanities (Master's Degree)",
                "Euro-American Languages, Literatures and Philologies",
                "History and Civilisation",
                "Italian Studies",
                "Linguistics and Translation",
                "Peace Studies: Conflict Transformation and Development Cooperation",
                "Philosophy and Forms of Knowledge",
                "Studies on Ancient Egypt, Near and Middle East",
                "Automotive Engineering",
                "Aerospace Engineering (Master's Degree)",
                "Artificial Intelligence and Data Engineering",
                "Biomedical Engineering (Master's Degree)",
                "Bionics Engineering",
                "Chemical Engineering (Master's Degree)",
                "Civil Infrastructures and Environmental Engineering",
                "Computer Engineering (Master's Degree)",
                "Cybersecurity",
                "Electric Engineering",
                "Electronic Engineering (Master's Degree)",
                "Energy Engineering (Master's Degree)",
                "Management Engineering (Master's Degree)",
                "Materials and Nanotechnology",
                "Mechanical Engineering (Master's Degree)",
                "Nuclear Engineering",
                "Robotics and Automation Engineering",
                "Structural and Building Engineering",
                "Technology and Production of Paper and Cardboard",
                "Telecommunications Engineering (Master's Degree)",
                "Clinical Psychology and Behavioral Sciences",
                "Health Professions of Rehabilitation Sciences",
                "Human Nutritional Sciences",
                "Nursing and Midwifery Sciences",
                "Sport Science for Prevention and Rehabilitation",
                "Innovation Law for Business and Institutions",
                "Institutions, Politics and Society",
                "Banking Finance Financial Markets",
                "Corporate Communication and Human Resources Management",
                "Economics (Master's Degree)",
                "European Union, Global Processes and Sustainable Development",
                "Management and Control of Logistic Processes",
                "Marketing and Market Research",
                "Maritime and Naval Science (Master's Degree)",
                "Planning and Governance of Tourism System in Mediterranean Area",
                "Professional Advice to Business",
                "Social Service Management and Innovation, Social Entrepreneurship and Third Sector Management",
                "Strategy, Management and Control",
                "Biology Applied to Biomedical Sciences",
                "Biotechnologies and Applied Artificial Intelligence for Health",
                "Chemistry (Master's Degree)",
                "Computer Science (Master's Degree)",
                "Computer Science and Networking",
                "Conservation and Evolution",
                "Data Science and Business Informatics",
                "Environmental Science",
                "Exploration and Applied Geophysics",
                "Geosciences and Geotechnologies",
                "Industrial Chemistry",
                "Informatics for Digital Health",
                "Marine Biology",
                "Mathematics (Master's Degree)",
                "Molecular and Cellular Biology",
                "Molecular Biotechnology",
                "Neuroscience",
                "Physics (Master's Degree)"

        );

        for (String degreeCourseName : degreeCourses) {
            DegreeCourseDTO degreeCourseDTO = new DegreeCourseDTO();
            degreeCourseDTO.setName(degreeCourseName);

            degreeCourseService.createDegreeCourse(degreeCourseDTO);

        }

    }
}
