package it.epicode.capstone.profession;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.ApplicationArguments;
import org.springframework.boot.ApplicationRunner;
import org.springframework.stereotype.Component;

import java.util.Arrays;
import java.util.List;

public class ProfessionRunner implements ApplicationRunner {

    @Autowired
    private ProfessionService professionService;

    @Override
    public void run(ApplicationArguments args) throws Exception {

        List<String> professioni = Arrays.asList(
                "Dentist",
                "Dermatologist",
                "Nurse Practitioner",
                "Occupational Therapist",
                "Ophthalmologist",
                "Optometrist",
                "Orthodontist",
                "Pediatrician",
                "Pharmacist",
                "Physician",
                "Radiologic Technologist",
                "Veterinarian",
                "Cosmetic Surgeon",
                "Endocrinologist",
                "Pediatric Nurse",
                "Pharmacologist",
                "Physician Assistant",
                "Psychotherapist",
                "Rehabilitation Counselor",
                "Medical Director",
                "Health Administrator",
                "Public Health Specialist",
                "Health Educator",
                "Clinical Research Coordinator",
                "Genetic Counselor",
                "Occupational Health Specialist",
                "Medical Laboratory Scientist",
                "Nutritionist",
                "Psychologist",
                "Clinical Psychologist",
                "Epidemiologist",
                "Aerospace Engineer",
                "Electronic Engineer",
                "Biomedical Engineer",
                "Chemical Engineer",
                "Civil Engineer",
                "Electrical Engineer",
                "Environmental Engineer",
                "Industrial Engineer",
                "Mechanical Engineer",
                "Mining Engineer",
                "Petroleum Engineer",
                "Construction Manager",
                "Telecommunications Engineer",
                "Metallurgical Engineer",
                "Nuclear Engineer",
                "Petroleum Geologist",
                "Rehabilitation Engineer",
                "Robotics Engineer",
                "Semiconductor Engineer",
                "Computer Scientist",
                "Data Analyst",
                "Data Scientist",
                "Information Systems Manager",
                "Information Technology Specialist",
                "Software Engineer",
                "Software Developer",
                "Cybersecurity Analyst",
                "Database Administrator",
                "Web Developer",
                "Systems Analyst",
                "Software Architect",
                "Technical Project Manager",
                "Network Engineer",
                "Astronaut",
                "Astronomer",
                "Biochemist",
                "Biologist",
                "Chemist",
                "Forensic Scientist",
                "Geologist",
                "Geophysicist",
                "Mathematician",
                "Microbiologist",
                "Neuroscientist",
                "Physicist",
                "Zoologist",
                "Biostatistician",
                "Molecular Biologist",
                "Materials Scientist",
                "Marine Biologist",
                "Statistician",
                "Research Scientist",
                "Geospatial Analyst",
                "Environmental Scientist",
                "Anthropologist",
                "Archaeologist",
                "Art Historian",
                "Economist",
                "Historian",
                "International Relations Specialist",
                "Political Scientist",
                "Sociologist",
                "Translator",
                "Political Consultant",
                "Research Psychologist",
                "Social Psychologist",
                "Urban Studies Researcher",
                "Philosopher",
                "Musicologist",
                "Accountant",
                "Actuary",
                "Business Analyst",
                "Financial Analyst",
                "Human Resources Manager",
                "Logistics Manager",
                "Management Consultant",
                "Marketing Manager",
                "Operations Manager",
                "Project Manager",
                "Quality Assurance Manager",
                "Risk Manager",
                "Sales Manager",
                "Tax Consultant",
                "Financial Manager",
                "Forensic Accountant",
                "Operations Research Analyst",
                "Risk Analyst",
                "Strategic Planner",
                "Corporate Trainer",
                "Digital Marketing Specialist",
                "Investment Banker",
                "Corporate Lawyer",
                "Lawyer",
                "Legal Consultant",
                "Patent Attorney",
                "School Counselor",
                "University Professor",
                "School Principal",
                "Librarian",
                "Instructional Designer",
                "Archivist",
                "Architect",
                "Graphic Designer",
                "Video Game Designer",
                "Industrial Designer",
                "Interior Designer",
                "Urban Planner",
                "Aortic Surgeon",
                "Anesthesiologist",
                "Psychiatrist",
                "Obstetrician",
                "Gynecologist",
                "Cardiologist",
                "General Surgeon",
                "Pathologist",
                "Radiologist",
                "Urologist",
                "Gastroenterologist",
                "Nephrologist",
                "Pulmonologist",
                "Hematologist",
                "Infectious Disease Specialist",
                "Medical Geneticist",
                "Control Systems Engineer",
                "Marine Engineer",
                "UX Designer",
                "Software Tester",
                "Business Intelligence Analyst",
                "Cloud Engineer",
                "Ecologist",
                "Botanist",
                "Climatologist",
                "Hydrologist",
                "Oceanographer",
                "Criminologist",
                "Demographer",
                "Linguist",
                "Business Development Manager",
                "Operations Analyst",
                "Product Manager",
                "Compliance Officer",
                "Art Director",
                "Multimedia Designer",
                "Fashion Designer",
                "Animator",
                "Journalist",
                "Data Engineer",
                "Geographer"
        );

        for (String nome : professioni) {
            ProfessionDTO professionDTO = new ProfessionDTO();
            professionDTO.setName(nome);
            professionService.createProfession(professionDTO);
        }
    }
}
